version: '3'
services:
  mongo:
    image: 'docker.io/library/mongo:4.4.11'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'cocoon'
      MONGO_INITDB_ROOT_PASSWORD: 'cocoon'
    volumes:
      - ./mongo:/etc/mongo
  mysql:
    image: 'docker.io/library/mysql:5.7.37'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'cocoon'
      MYSQL_DATABASE: 'cocoon'
      MYSQL_USER: 'cocoon'
      MYSQL_PASSWORD: 'cocoon'
    volumes:
      - ./mysql:/var/lib/mysql